### PR TITLE
Upgrade to polkadot2412

### PR DESCRIPTION
**Pull request by goozang-records**
- [x] fork rust-ethereum/ethereum to pin required changes recently merged to master
- [x] fork + update rust-ethereum/evm to work with primitive-types = 0.13 which is required by sp_core in stable2412
- [x] update primitive types U256::to_big_endian usage calls to not take any input
- [x] update  fp-evm to latest evm API
- [x] update fp-rpc to latest evm API 
- [x] update fp-self-contained to latest evm API
- [ ] (WIP) update frame-evm/runner to use latest Stack API

### CODE REVIEW

**Comment by libreamartists** [comment]
Updating fp-evm to latest rust-ethereum/evm API is progressing slowly. I am working through compilation errors related to updated directory structure, refactored types generated by macros, a new Gasometer API, and a new precompile API.

**Comment by libreamartists** [comment]
replaced by #4
